-- begin BRC_ORDER
alter table BRC_ORDER add constraint FK_BRC_ORDER_ON_REQUEST_ITEM foreign key (REQUEST_ITEM_ID) references BRC_REQUEST_ITEM(ID)^
create index IDX_BRC_ORDER_ON_REQUEST_ITEM on BRC_ORDER (REQUEST_ITEM_ID)^
-- end BRC_ORDER
-- begin BRC_REQUEST_ITEM
alter table BRC_REQUEST_ITEM add constraint FK_BRC_REQUEST_ITEM_ON_REQUEST foreign key (REQUEST_ID) references BRC_REQUEST(ID)^
alter table BRC_REQUEST_ITEM add constraint FK_BRC_REQUEST_ITEM_ON_ITEM foreign key (ITEM_ID) references BRC_ITEM(ID)^
create index IDX_BRC_REQUEST_ITEM_ON_REQUEST on BRC_REQUEST_ITEM (REQUEST_ID)^
create index IDX_BRC_REQUEST_ITEM_ON_ITEM on BRC_REQUEST_ITEM (ITEM_ID)^
-- end BRC_REQUEST_ITEM
-- begin BRC_REQUEST
alter table BRC_REQUEST add constraint FK_BRC_REQUEST_ON_REQUEST_TYPE foreign key (REQUEST_TYPE_ID) references BRC_REQUEST_TYPE(ID)^
create index IDX_BRC_REQUEST_ON_REQUEST_TYPE on BRC_REQUEST (REQUEST_TYPE_ID)^
-- end BRC_REQUEST
-- begin BRC_ITEM
alter table BRC_ITEM add constraint FK_BRC_ITEM_ON_CATEGORY foreign key (CATEGORY_ID) references BRC_CATEGORY(ID)^
alter table BRC_ITEM add constraint FK_BRC_ITEM_ON_UNIT foreign key (UNIT_ID) references BRC_ITEM_UNIT(ID)^
create index IDX_BRC_ITEM_ON_CATEGORY on BRC_ITEM (CATEGORY_ID)^
create index IDX_BRC_ITEM_ON_UNIT on BRC_ITEM (UNIT_ID)^
-- end BRC_ITEM
-- begin BRC_TASK
alter table BRC_TASK add constraint FK_BRC_TASK_ON_EXECUTOR foreign key (EXECUTOR_ID) references SEC_USER(ID)^
alter table BRC_TASK add constraint FK_BRC_TASK_ON_FROM foreign key (FROM_ID) references SEC_USER(ID)^
create index IDX_BRC_TASK_ON_EXECUTOR on BRC_TASK (EXECUTOR_ID)^
create index IDX_BRC_TASK_ON_FROM on BRC_TASK (FROM_ID)^
-- end BRC_TASK
-- begin BRC_MEASURING_DEVICE
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_NAME foreign key (NAME_ID) references BRC_MEASURE_DEVICE_NAME(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_MEASURE_TYPE foreign key (MEASURE_TYPE_ID) references BRC_MEASURE_TYPE(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_UNIT foreign key (UNIT_ID) references BRC_UNIT(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_CALI_UP_INTERVAL foreign key (CALI_UP_INTERVAL_ID) references BRC_CALI_UP_INTERVAL(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_CALI_UP foreign key (CALI_UP_ID) references BRC_CALI_UP(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_PASSPORT foreign key (PASSPORT_ID) references BRC_PASSPORT(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_ACCOUNTING foreign key (ACCOUNTING_ID) references BRC_ACCOUNTING(ID)^
alter table BRC_MEASURING_DEVICE add constraint FK_BRC_MEASURING_DEVICE_ON_ATTACHMENT foreign key (ATTACHMENT_ID) references BRC_ATTACHMENT(ID)^
create unique index IDX_BRC_MEASURING_DEVICE_UK_BARCODE on BRC_MEASURING_DEVICE (BARCODE) where DELETE_TS is null ^
create index IDX_BRC_MEASURING_DEVICE_ON_NAME on BRC_MEASURING_DEVICE (NAME_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_MEASURE_TYPE on BRC_MEASURING_DEVICE (MEASURE_TYPE_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_UNIT on BRC_MEASURING_DEVICE (UNIT_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_CALI_UP_INTERVAL on BRC_MEASURING_DEVICE (CALI_UP_INTERVAL_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_CALI_UP on BRC_MEASURING_DEVICE (CALI_UP_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_PASSPORT on BRC_MEASURING_DEVICE (PASSPORT_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_ACCOUNTING on BRC_MEASURING_DEVICE (ACCOUNTING_ID)^
create index IDX_BRC_MEASURING_DEVICE_ON_ATTACHMENT on BRC_MEASURING_DEVICE (ATTACHMENT_ID)^
-- end BRC_MEASURING_DEVICE

-- begin BRC_MEASURE
alter table BRC_MEASURE add constraint FK_BRC_MEASURE_ON_POSITION foreign key (POSITION_ID) references BRC_POSITION(ID)^
alter table BRC_MEASURE add constraint FK_BRC_MEASURE_ON_CALI_UP_TYPE foreign key (CALI_UP_TYPE_ID) references BRC_CALI_UP_TYPE(ID)^
alter table BRC_MEASURE add constraint FK_BRC_MEASURE_ON_MEASURE_TYPE foreign key (MEASURE_TYPE_ID) references BRC_MEASURE_TYPE(ID)^
alter table BRC_MEASURE add constraint FK_BRC_MEASURE_ON_RED_VALUE_UNIT foreign key (RED_VALUE_UNIT_ID) references BRC_UNIT(ID)^
alter table BRC_MEASURE add constraint FK_BRC_MEASURE_ON_ATTACHMENT foreign key (ATTACHMENT_ID) references BRC_ATTACHMENT(ID)^
create index IDX_BRC_MEASURE_ON_POSITION on BRC_MEASURE (POSITION_ID)^
create index IDX_BRC_MEASURE_ON_CALI_UP_TYPE on BRC_MEASURE (CALI_UP_TYPE_ID)^
create index IDX_BRC_MEASURE_ON_MEASURE_TYPE on BRC_MEASURE (MEASURE_TYPE_ID)^
create index IDX_BRC_MEASURE_ON_RED_VALUE_UNIT on BRC_MEASURE (RED_VALUE_UNIT_ID)^
create index IDX_BRC_MEASURE_ON_ATTACHMENT on BRC_MEASURE (ATTACHMENT_ID)^
-- end BRC_MEASURE
-- begin BRC_CONTRACT_ORDER
alter table BRC_CONTRACT_ORDER add constraint FK_BRC_CONTRACT_ORDER_ON_CONTRACT foreign key (CONTRACT_ID) references BRC_CONTRACT(ID)^
create index IDX_BRC_CONTRACT_ORDER_ON_CONTRACT on BRC_CONTRACT_ORDER (CONTRACT_ID)^
-- end BRC_CONTRACT_ORDER
-- begin BRC_CONTRACT
alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_FIRM foreign key (FIRM_ID) references BRC_FIRM(ID)^
alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_VALUE_OF_VAT foreign key (VALUE_OF_VAT_ID) references BRC_VAT(ID)^
alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_WORKS_TYPE foreign key (WORKS_TYPE_ID) references BRC_WORKS_TYPE(ID)^
alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_PAY_TYPE foreign key (PAY_TYPE_ID) references BRC_PAY_TYPE(ID)^
alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_PAY_ATTACHMENT foreign key (PAY_ATTACHMENT_ID) references BRC_PAY_ATTACHMENT(ID)^
alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_STATUS foreign key (STATUS_ID) references BRC_CONTRACT_STATUS(ID)^
create index IDX_BRC_CONTRACT_ON_FIRM on BRC_CONTRACT (FIRM_ID)^
create index IDX_BRC_CONTRACT_ON_VALUE_OF_VAT on BRC_CONTRACT (VALUE_OF_VAT_ID)^
create index IDX_BRC_CONTRACT_ON_WORKS_TYPE on BRC_CONTRACT (WORKS_TYPE_ID)^
create index IDX_BRC_CONTRACT_ON_PAY_TYPE on BRC_CONTRACT (PAY_TYPE_ID)^
create index IDX_BRC_CONTRACT_ON_PAY_ATTACHMENT on BRC_CONTRACT (PAY_ATTACHMENT_ID)^
create index IDX_BRC_CONTRACT_ON_STATUS on BRC_CONTRACT (STATUS_ID)^
-- end BRC_CONTRACT
-- begin BRC_MEASURE_DEVICE_PACKAGE
alter table BRC_MEASURE_DEVICE_PACKAGE add constraint FK_BRC_MEASURE_DEVICE_PACKAGE_ON_FROM_POSITION foreign key (FROM_POSITION_ID) references BRC_POSITION(ID)^
alter table BRC_MEASURE_DEVICE_PACKAGE add constraint FK_BRC_MEASURE_DEVICE_PACKAGE_ON_TO_DESTINATION foreign key (TO_DESTINATION_ID) references BRC_POSITION(ID)^
alter table BRC_MEASURE_DEVICE_PACKAGE add constraint FK_BRC_MEASURE_DEVICE_PACKAGE_ON_CONTRACT foreign key (CONTRACT_ID) references BRC_CONTRACT(ID)^
create index IDX_BRC_MEASURE_DEVICE_PACKAGE_ON_FROM_POSITION on BRC_MEASURE_DEVICE_PACKAGE (FROM_POSITION_ID)^
create index IDX_BRC_MEASURE_DEVICE_PACKAGE_ON_TO_DESTINATION on BRC_MEASURE_DEVICE_PACKAGE (TO_DESTINATION_ID)^
create index IDX_BRC_MEASURE_DEVICE_PACKAGE_ON_CONTRACT on BRC_MEASURE_DEVICE_PACKAGE (CONTRACT_ID)^
-- end BRC_MEASURE_DEVICE_PACKAGE
-- begin BRC_MEASURE_DEVICE_PACKAGE_MEASURING_DEVICE_LINK
alter table BRC_MEASURE_DEVICE_PACKAGE_MEASURING_DEVICE_LINK add constraint FK_MEADEVPACMEADEV_ON_MEASURE_DEVICE_PACKAGE foreign key (MEASURE_DEVICE_PACKAGE_ID) references BRC_MEASURE_DEVICE_PACKAGE(ID)^
alter table BRC_MEASURE_DEVICE_PACKAGE_MEASURING_DEVICE_LINK add constraint FK_MEADEVPACMEADEV_ON_MEASURING_DEVICE foreign key (MEASURING_DEVICE_ID) references BRC_MEASURING_DEVICE(ID)^
-- end BRC_MEASURE_DEVICE_PACKAGE_MEASURING_DEVICE_LINK
-- begin BRC_CONTRACT_ORDER_MEASURE_DEVICE_PACKAGE_LINK
alter table BRC_CONTRACT_ORDER_MEASURE_DEVICE_PACKAGE_LINK add constraint FK_CONORDMEADEVPAC_ON_CONTRACT_ORDER foreign key (CONTRACT_ORDER_ID) references BRC_CONTRACT_ORDER(ID)^
alter table BRC_CONTRACT_ORDER_MEASURE_DEVICE_PACKAGE_LINK add constraint FK_CONORDMEADEVPAC_ON_MEASURE_DEVICE_PACKAGE foreign key (MEASURE_DEVICE_PACKAGE_ID) references BRC_MEASURE_DEVICE_PACKAGE(ID)^
-- end BRC_CONTRACT_ORDER_MEASURE_DEVICE_PACKAGE_LINK
-- begin BRC_MEASURE_DEVICE_NAME
alter table BRC_MEASURE_DEVICE_NAME add constraint FK_BRC_MEASURE_DEVICE_NAME_ON_MEASURE_DEVICE_NODE foreign key (MEASURE_DEVICE_NODE_ID) references BRC_MEASURE_DEVICE_NAME(ID)^
create index IDX_BRC_MEASURE_DEVICE_NAME_ON_MEASURE_DEVICE_NODE on BRC_MEASURE_DEVICE_NAME (MEASURE_DEVICE_NODE_ID)^
-- end BRC_MEASURE_DEVICE_NAME
-- begin BRC_FIRM
alter table BRC_FIRM add constraint FK_BRC_FIRM_ON_POSITION foreign key (POSITION_ID) references BRC_POSITION(ID)^
create index IDX_BRC_FIRM_ON_POSITION on BRC_FIRM (POSITION_ID)^
-- end BRC_FIRM

-- begin BRC_PASSPORT_MEASURING_DEVICE_LINK
alter table BRC_PASSPORT_MEASURING_DEVICE_LINK add constraint FK_PASMEADEV_ON_PASSPORT foreign key (PASSPORT_ID) references BRC_PASSPORT(ID)^
alter table BRC_PASSPORT_MEASURING_DEVICE_LINK add constraint FK_PASMEADEV_ON_MEASURING_DEVICE foreign key (MEASURING_DEVICE_ID) references BRC_MEASURING_DEVICE(ID)^
-- end BRC_PASSPORT_MEASURING_DEVICE_LINK
-- begin BRC_SERVICE_MEASURE_DEVICE_NAME_LINK
alter table BRC_SERVICE_MEASURE_DEVICE_NAME_LINK add constraint FK_SERMEADEVNAM_ON_SERVICE foreign key (SERVICE_ID) references BRC_SERVICE(ID)^
alter table BRC_SERVICE_MEASURE_DEVICE_NAME_LINK add constraint FK_SERMEADEVNAM_ON_MEASURE_DEVICE_NAME foreign key (MEASURE_DEVICE_NAME_ID) references BRC_MEASURE_DEVICE_NAME(ID)^
-- end BRC_SERVICE_MEASURE_DEVICE_NAME_LINK
-- begin BRC_ATTACHMENT
alter table BRC_ATTACHMENT add constraint FK_BRC_ATTACHMENT_ON_ATTACHMENT_NODE foreign key (ATTACHMENT_NODE_ID) references BRC_ATTACHMENT(ID)^
create index IDX_BRC_ATTACHMENT_ON_ATTACHMENT_NODE on BRC_ATTACHMENT (ATTACHMENT_NODE_ID)^
-- end BRC_ATTACHMENT
-- begin BRC_CALI_UP
alter table BRC_CALI_UP add constraint FK_BRC_CALI_UP_ON_CALI_UP_TYPE foreign key (CALI_UP_TYPE_ID) references BRC_CALI_UP_TYPE(ID)^
alter table BRC_CALI_UP add constraint FK_BRC_CALI_UP_ON_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID)^
create index IDX_BRC_CALI_UP_ON_CALI_UP_TYPE on BRC_CALI_UP (CALI_UP_TYPE_ID)^
create index IDX_BRC_CALI_UP_ON_DOCUMENT on BRC_CALI_UP (DOCUMENT_ID)^
-- end BRC_CALI_UP
-- begin BRC_POSITION
alter table BRC_POSITION add constraint FK_BRC_POSITION_ON_POSITION_NODE foreign key (POSITION_NODE_ID) references BRC_POSITION(ID)^
alter table BRC_POSITION add constraint FK_BRC_POSITION_ON_ATTACHMENT foreign key (ATTACHMENT_ID) references BRC_ATTACHMENT(ID)^
create index IDX_BRC_POSITION_ON_POSITION_NODE on BRC_POSITION (POSITION_NODE_ID)^
create index IDX_BRC_POSITION_ON_ATTACHMENT on BRC_POSITION (ATTACHMENT_ID)^
-- end BRC_POSITION
-- begin BRC_SERVICE
alter table BRC_SERVICE add constraint FK_BRC_SERVICE_ON_FIRM foreign key (FIRM_ID) references BRC_FIRM(ID)^
create index IDX_BRC_SERVICE_ON_FIRM on BRC_SERVICE (FIRM_ID)^
-- end BRC_SERVICE
-- begin BRC_STATUS_ITEM
alter table BRC_STATUS_ITEM add constraint FK_BRC_STATUS_ITEM_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table BRC_STATUS_ITEM add constraint FK_BRC_STATUS_ITEM_ON_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID)^
alter table BRC_STATUS_ITEM add constraint FK_BRC_STATUS_ITEM_ON_MEASURING_DEVICE foreign key (MEASURING_DEVICE_ID) references BRC_MEASURING_DEVICE(ID)^
create index IDX_BRC_STATUS_ITEM_ON_USER on BRC_STATUS_ITEM (USER_ID)^
create index IDX_BRC_STATUS_ITEM_ON_DOCUMENT on BRC_STATUS_ITEM (DOCUMENT_ID)^
create index IDX_BRC_STATUS_ITEM_ON_MEASURING_DEVICE on BRC_STATUS_ITEM (MEASURING_DEVICE_ID)^
-- end BRC_STATUS_ITEM
