alter table BRC_STATUS_ITEM add constraint FK_BRC_STATUS_ITEM_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table BRC_STATUS_ITEM add constraint FK_BRC_STATUS_ITEM_ON_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
alter table BRC_STATUS_ITEM add constraint FK_BRC_STATUS_ITEM_ON_MEASURING_DEVICE foreign key (MEASURING_DEVICE_ID) references BRC_MEASURING_DEVICE(ID);
create index IDX_BRC_STATUS_ITEM_ON_USER on BRC_STATUS_ITEM (USER_ID);
create index IDX_BRC_STATUS_ITEM_ON_DOCUMENT on BRC_STATUS_ITEM (DOCUMENT_ID);
create index IDX_BRC_STATUS_ITEM_ON_MEASURING_DEVICE on BRC_STATUS_ITEM (MEASURING_DEVICE_ID);
