alter table BRC_CONTRACT add constraint FK_BRC_CONTRACT_ON_PAY_ATTACHMENT foreign key (PAY_ATTACHMENT_ID) references BRC_PAY_ATTACHMENT(ID);
create index IDX_BRC_CONTRACT_ON_PAY_ATTACHMENT on BRC_CONTRACT (PAY_ATTACHMENT_ID);
