alter table BRC_REQUEST add constraint FK_BRC_REQUEST_ON_REQUEST_TYPE foreign key (REQUEST_TYPE_ID) references BRC_REQUEST_TYPE(ID);
create index IDX_BRC_REQUEST_ON_REQUEST_TYPE on BRC_REQUEST (REQUEST_TYPE_ID);
