alter table BRC_ATTACHMENT add constraint FK_BRC_ATTACHMENT_ON_ATTACHMENT_NODE foreign key (ATTACHMENT_NODE_ID) references BRC_ATTACHMENT(ID);
create index IDX_BRC_ATTACHMENT_ON_ATTACHMENT_NODE on BRC_ATTACHMENT (ATTACHMENT_NODE_ID);
