alter table BRC_POSITION add constraint FK_BRC_POSITION_ON_POSITION_NODE foreign key (POSITION_NODE_ID) references BRC_POSITION(ID);
alter table BRC_POSITION add constraint FK_BRC_POSITION_ON_ATTACHMENT foreign key (ATTACHMENT_ID) references BRC_ATTACHMENT(ID);
create index IDX_BRC_POSITION_ON_POSITION_NODE on BRC_POSITION (POSITION_NODE_ID);
create index IDX_BRC_POSITION_ON_ATTACHMENT on BRC_POSITION (ATTACHMENT_ID);
